#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="License.Busiwiz")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_PageHelp(tbl_PageHelp instance);
  partial void Updatetbl_PageHelp(tbl_PageHelp instance);
  partial void Deletetbl_PageHelp(tbl_PageHelp instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LicenseBusiwizConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_PageHelp> tbl_PageHelps
	{
		get
		{
			return this.GetTable<tbl_PageHelp>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PageHelp")]
public partial class tbl_PageHelp : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PageHelpID;
	
	private string _ImageTitle;
	
	private string _ScreenShotPath;
	
	private string _VideoTitle;
	
	private string _VideoPath;
	
	private string _Description;
	
	private string _PdfTitle;
	
	private string _PdfPath;
	
	private System.Nullable<int> _Menu;
	
	private System.Nullable<int> _SubMenu;
	
	private System.Nullable<int> _Product;
	
	private System.Nullable<int> _PageMasterID;
	
	private System.Nullable<bool> _Active;
	
	private System.Nullable<int> _VersionID;
	
	private int _MasterPageID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPageHelpIDChanging(int value);
    partial void OnPageHelpIDChanged();
    partial void OnImageTitleChanging(string value);
    partial void OnImageTitleChanged();
    partial void OnScreenShotPathChanging(string value);
    partial void OnScreenShotPathChanged();
    partial void OnVideoTitleChanging(string value);
    partial void OnVideoTitleChanged();
    partial void OnVideoPathChanging(string value);
    partial void OnVideoPathChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPdfTitleChanging(string value);
    partial void OnPdfTitleChanged();
    partial void OnPdfPathChanging(string value);
    partial void OnPdfPathChanged();
    partial void OnMenuChanging(System.Nullable<int> value);
    partial void OnMenuChanged();
    partial void OnSubMenuChanging(System.Nullable<int> value);
    partial void OnSubMenuChanged();
    partial void OnProductChanging(System.Nullable<int> value);
    partial void OnProductChanged();
    partial void OnPageMasterIDChanging(System.Nullable<int> value);
    partial void OnPageMasterIDChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnVersionIDChanging(System.Nullable<int> value);
    partial void OnVersionIDChanged();
    partial void OnMasterPageIDChanging(int value);
    partial void OnMasterPageIDChanged();
    #endregion
	
	public tbl_PageHelp()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageHelpID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int PageHelpID
	{
		get
		{
			return this._PageHelpID;
		}
		set
		{
			if ((this._PageHelpID != value))
			{
				this.OnPageHelpIDChanging(value);
				this.SendPropertyChanging();
				this._PageHelpID = value;
				this.SendPropertyChanged("PageHelpID");
				this.OnPageHelpIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageTitle", DbType="VarChar(100)")]
	public string ImageTitle
	{
		get
		{
			return this._ImageTitle;
		}
		set
		{
			if ((this._ImageTitle != value))
			{
				this.OnImageTitleChanging(value);
				this.SendPropertyChanging();
				this._ImageTitle = value;
				this.SendPropertyChanged("ImageTitle");
				this.OnImageTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScreenShotPath", DbType="VarChar(MAX)")]
	public string ScreenShotPath
	{
		get
		{
			return this._ScreenShotPath;
		}
		set
		{
			if ((this._ScreenShotPath != value))
			{
				this.OnScreenShotPathChanging(value);
				this.SendPropertyChanging();
				this._ScreenShotPath = value;
				this.SendPropertyChanged("ScreenShotPath");
				this.OnScreenShotPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoTitle", DbType="VarChar(MAX)")]
	public string VideoTitle
	{
		get
		{
			return this._VideoTitle;
		}
		set
		{
			if ((this._VideoTitle != value))
			{
				this.OnVideoTitleChanging(value);
				this.SendPropertyChanging();
				this._VideoTitle = value;
				this.SendPropertyChanged("VideoTitle");
				this.OnVideoTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoPath", DbType="VarChar(MAX)")]
	public string VideoPath
	{
		get
		{
			return this._VideoPath;
		}
		set
		{
			if ((this._VideoPath != value))
			{
				this.OnVideoPathChanging(value);
				this.SendPropertyChanging();
				this._VideoPath = value;
				this.SendPropertyChanged("VideoPath");
				this.OnVideoPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PdfTitle", DbType="VarChar(256)")]
	public string PdfTitle
	{
		get
		{
			return this._PdfTitle;
		}
		set
		{
			if ((this._PdfTitle != value))
			{
				this.OnPdfTitleChanging(value);
				this.SendPropertyChanging();
				this._PdfTitle = value;
				this.SendPropertyChanged("PdfTitle");
				this.OnPdfTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PdfPath", DbType="VarChar(MAX)")]
	public string PdfPath
	{
		get
		{
			return this._PdfPath;
		}
		set
		{
			if ((this._PdfPath != value))
			{
				this.OnPdfPathChanging(value);
				this.SendPropertyChanging();
				this._PdfPath = value;
				this.SendPropertyChanged("PdfPath");
				this.OnPdfPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu", DbType="Int")]
	public System.Nullable<int> Menu
	{
		get
		{
			return this._Menu;
		}
		set
		{
			if ((this._Menu != value))
			{
				this.OnMenuChanging(value);
				this.SendPropertyChanging();
				this._Menu = value;
				this.SendPropertyChanged("Menu");
				this.OnMenuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubMenu", DbType="Int")]
	public System.Nullable<int> SubMenu
	{
		get
		{
			return this._SubMenu;
		}
		set
		{
			if ((this._SubMenu != value))
			{
				this.OnSubMenuChanging(value);
				this.SendPropertyChanging();
				this._SubMenu = value;
				this.SendPropertyChanged("SubMenu");
				this.OnSubMenuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="Int")]
	public System.Nullable<int> Product
	{
		get
		{
			return this._Product;
		}
		set
		{
			if ((this._Product != value))
			{
				this.OnProductChanging(value);
				this.SendPropertyChanging();
				this._Product = value;
				this.SendPropertyChanged("Product");
				this.OnProductChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageMasterID", DbType="Int")]
	public System.Nullable<int> PageMasterID
	{
		get
		{
			return this._PageMasterID;
		}
		set
		{
			if ((this._PageMasterID != value))
			{
				this.OnPageMasterIDChanging(value);
				this.SendPropertyChanging();
				this._PageMasterID = value;
				this.SendPropertyChanged("PageMasterID");
				this.OnPageMasterIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionID", DbType="Int")]
	public System.Nullable<int> VersionID
	{
		get
		{
			return this._VersionID;
		}
		set
		{
			if ((this._VersionID != value))
			{
				this.OnVersionIDChanging(value);
				this.SendPropertyChanging();
				this._VersionID = value;
				this.SendPropertyChanged("VersionID");
				this.OnVersionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterPageID")]
	public int MasterPageID
	{
		get
		{
			return this._MasterPageID;
		}
		set
		{
			if ((this._MasterPageID != value))
			{
				this.OnMasterPageIDChanging(value);
				this.SendPropertyChanging();
				this._MasterPageID = value;
				this.SendPropertyChanged("MasterPageID");
				this.OnMasterPageIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
