#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="jobcenter.INTMSGDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMsgDetail(MsgDetail instance);
  partial void UpdateMsgDetail(MsgDetail instance);
  partial void DeleteMsgDetail(MsgDetail instance);
  partial void InsertMsgFileAttachDetail(MsgFileAttachDetail instance);
  partial void UpdateMsgFileAttachDetail(MsgFileAttachDetail instance);
  partial void DeleteMsgFileAttachDetail(MsgFileAttachDetail instance);
  partial void InsertMsgMaster(MsgMaster instance);
  partial void UpdateMsgMaster(MsgMaster instance);
  partial void DeleteMsgMaster(MsgMaster instance);
  partial void InsertMsgStatusMaster(MsgStatusMaster instance);
  partial void UpdateMsgStatusMaster(MsgStatusMaster instance);
  partial void DeleteMsgStatusMaster(MsgStatusMaster instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["jobcenter_INTMSGDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<MsgDetail> MsgDetails
	{
		get
		{
			return this.GetTable<MsgDetail>();
		}
	}
	
	public System.Data.Linq.Table<MsgFileAttachDetail> MsgFileAttachDetails
	{
		get
		{
			return this.GetTable<MsgFileAttachDetail>();
		}
	}
	
	public System.Data.Linq.Table<MsgMaster> MsgMasters
	{
		get
		{
			return this.GetTable<MsgMaster>();
		}
	}
	
	public System.Data.Linq.Table<MsgStatusMaster> MsgStatusMasters
	{
		get
		{
			return this.GetTable<MsgStatusMaster>();
		}
	}
	
	public System.Data.Linq.Table<Party_master> Party_masters
	{
		get
		{
			return this.GetTable<Party_master>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MsgDetail")]
public partial class MsgDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MsgDetailId;
	
	private int _MsgId;
	
	private int _ToPartyId;
	
	private int _MsgStatusId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsgDetailIdChanging(int value);
    partial void OnMsgDetailIdChanged();
    partial void OnMsgIdChanging(int value);
    partial void OnMsgIdChanged();
    partial void OnToPartyIdChanging(int value);
    partial void OnToPartyIdChanged();
    partial void OnMsgStatusIdChanging(int value);
    partial void OnMsgStatusIdChanged();
    #endregion
	
	public MsgDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgDetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MsgDetailId
	{
		get
		{
			return this._MsgDetailId;
		}
		set
		{
			if ((this._MsgDetailId != value))
			{
				this.OnMsgDetailIdChanging(value);
				this.SendPropertyChanging();
				this._MsgDetailId = value;
				this.SendPropertyChanged("MsgDetailId");
				this.OnMsgDetailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgId", DbType="Int NOT NULL")]
	public int MsgId
	{
		get
		{
			return this._MsgId;
		}
		set
		{
			if ((this._MsgId != value))
			{
				this.OnMsgIdChanging(value);
				this.SendPropertyChanging();
				this._MsgId = value;
				this.SendPropertyChanged("MsgId");
				this.OnMsgIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToPartyId", DbType="Int NOT NULL")]
	public int ToPartyId
	{
		get
		{
			return this._ToPartyId;
		}
		set
		{
			if ((this._ToPartyId != value))
			{
				this.OnToPartyIdChanging(value);
				this.SendPropertyChanging();
				this._ToPartyId = value;
				this.SendPropertyChanged("ToPartyId");
				this.OnToPartyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgStatusId", DbType="Int NOT NULL")]
	public int MsgStatusId
	{
		get
		{
			return this._MsgStatusId;
		}
		set
		{
			if ((this._MsgStatusId != value))
			{
				this.OnMsgStatusIdChanging(value);
				this.SendPropertyChanging();
				this._MsgStatusId = value;
				this.SendPropertyChanged("MsgStatusId");
				this.OnMsgStatusIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MsgFileAttachDetail")]
public partial class MsgFileAttachDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MsgFileId;
	
	private int _MsgId;
	
	private string _FileName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsgFileIdChanging(int value);
    partial void OnMsgFileIdChanged();
    partial void OnMsgIdChanging(int value);
    partial void OnMsgIdChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    #endregion
	
	public MsgFileAttachDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgFileId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MsgFileId
	{
		get
		{
			return this._MsgFileId;
		}
		set
		{
			if ((this._MsgFileId != value))
			{
				this.OnMsgFileIdChanging(value);
				this.SendPropertyChanging();
				this._MsgFileId = value;
				this.SendPropertyChanged("MsgFileId");
				this.OnMsgFileIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgId", DbType="Int NOT NULL")]
	public int MsgId
	{
		get
		{
			return this._MsgId;
		}
		set
		{
			if ((this._MsgId != value))
			{
				this.OnMsgIdChanging(value);
				this.SendPropertyChanging();
				this._MsgId = value;
				this.SendPropertyChanged("MsgId");
				this.OnMsgIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string FileName
	{
		get
		{
			return this._FileName;
		}
		set
		{
			if ((this._FileName != value))
			{
				this.OnFileNameChanging(value);
				this.SendPropertyChanging();
				this._FileName = value;
				this.SendPropertyChanged("FileName");
				this.OnFileNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MsgMaster")]
public partial class MsgMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MsgId;
	
	private System.Nullable<int> _FromPartyId;
	
	private System.Nullable<System.DateTime> _MsgDate;
	
	private string _MsgSubject;
	
	private string _MsgDetail;
	
	private string _MsgStatus;
	
	private System.Nullable<bool> _Picture;
	
	private string _Signature;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsgIdChanging(int value);
    partial void OnMsgIdChanged();
    partial void OnFromPartyIdChanging(System.Nullable<int> value);
    partial void OnFromPartyIdChanged();
    partial void OnMsgDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMsgDateChanged();
    partial void OnMsgSubjectChanging(string value);
    partial void OnMsgSubjectChanged();
    partial void OnMsgDetailChanging(string value);
    partial void OnMsgDetailChanged();
    partial void OnMsgStatusChanging(string value);
    partial void OnMsgStatusChanged();
    partial void OnPictureChanging(System.Nullable<bool> value);
    partial void OnPictureChanged();
    partial void OnSignatureChanging(string value);
    partial void OnSignatureChanged();
    #endregion
	
	public MsgMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MsgId
	{
		get
		{
			return this._MsgId;
		}
		set
		{
			if ((this._MsgId != value))
			{
				this.OnMsgIdChanging(value);
				this.SendPropertyChanging();
				this._MsgId = value;
				this.SendPropertyChanged("MsgId");
				this.OnMsgIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromPartyId", DbType="Int")]
	public System.Nullable<int> FromPartyId
	{
		get
		{
			return this._FromPartyId;
		}
		set
		{
			if ((this._FromPartyId != value))
			{
				this.OnFromPartyIdChanging(value);
				this.SendPropertyChanging();
				this._FromPartyId = value;
				this.SendPropertyChanged("FromPartyId");
				this.OnFromPartyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> MsgDate
	{
		get
		{
			return this._MsgDate;
		}
		set
		{
			if ((this._MsgDate != value))
			{
				this.OnMsgDateChanging(value);
				this.SendPropertyChanging();
				this._MsgDate = value;
				this.SendPropertyChanged("MsgDate");
				this.OnMsgDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgSubject", DbType="NVarChar(500)")]
	public string MsgSubject
	{
		get
		{
			return this._MsgSubject;
		}
		set
		{
			if ((this._MsgSubject != value))
			{
				this.OnMsgSubjectChanging(value);
				this.SendPropertyChanging();
				this._MsgSubject = value;
				this.SendPropertyChanged("MsgSubject");
				this.OnMsgSubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgDetail", DbType="NVarChar(MAX)")]
	public string MsgDetail
	{
		get
		{
			return this._MsgDetail;
		}
		set
		{
			if ((this._MsgDetail != value))
			{
				this.OnMsgDetailChanging(value);
				this.SendPropertyChanging();
				this._MsgDetail = value;
				this.SendPropertyChanged("MsgDetail");
				this.OnMsgDetailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgStatus", DbType="NVarChar(50)")]
	public string MsgStatus
	{
		get
		{
			return this._MsgStatus;
		}
		set
		{
			if ((this._MsgStatus != value))
			{
				this.OnMsgStatusChanging(value);
				this.SendPropertyChanging();
				this._MsgStatus = value;
				this.SendPropertyChanged("MsgStatus");
				this.OnMsgStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Bit")]
	public System.Nullable<bool> Picture
	{
		get
		{
			return this._Picture;
		}
		set
		{
			if ((this._Picture != value))
			{
				this.OnPictureChanging(value);
				this.SendPropertyChanging();
				this._Picture = value;
				this.SendPropertyChanged("Picture");
				this.OnPictureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signature", DbType="NVarChar(MAX)")]
	public string Signature
	{
		get
		{
			return this._Signature;
		}
		set
		{
			if ((this._Signature != value))
			{
				this.OnSignatureChanging(value);
				this.SendPropertyChanging();
				this._Signature = value;
				this.SendPropertyChanged("Signature");
				this.OnSignatureChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MsgStatusMaster")]
public partial class MsgStatusMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MsgStatusId;
	
	private string _MsgStatusName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsgStatusIdChanging(int value);
    partial void OnMsgStatusIdChanged();
    partial void OnMsgStatusNameChanging(string value);
    partial void OnMsgStatusNameChanged();
    #endregion
	
	public MsgStatusMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgStatusId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MsgStatusId
	{
		get
		{
			return this._MsgStatusId;
		}
		set
		{
			if ((this._MsgStatusId != value))
			{
				this.OnMsgStatusIdChanging(value);
				this.SendPropertyChanging();
				this._MsgStatusId = value;
				this.SendPropertyChanged("MsgStatusId");
				this.OnMsgStatusIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgStatusName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string MsgStatusName
	{
		get
		{
			return this._MsgStatusName;
		}
		set
		{
			if ((this._MsgStatusName != value))
			{
				this.OnMsgStatusNameChanging(value);
				this.SendPropertyChanging();
				this._MsgStatusName = value;
				this.SendPropertyChanged("MsgStatusName");
				this.OnMsgStatusNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Party_master")]
public partial class Party_master
{
	
	private int _PartyID;
	
	private System.Nullable<int> _Account;
	
	private string _Compname;
	
	private string _Contactperson;
	
	private string _Address;
	
	private string _City;
	
	private string _State;
	
	private string _Country;
	
	private string _Website;
	
	private string _GSTno;
	
	private string _Incometaxno;
	
	private string _Email;
	
	private string _Phoneno;
	
	private System.Nullable<int> _DataopID;
	
	private System.Nullable<int> _PartyTypeId;
	
	private System.Nullable<int> _AssignedAccountManagerId;
	
	private System.Nullable<int> _AssignedRecevingDepartmentInchargeId;
	
	private System.Nullable<int> _AssignedPurchaseDepartmentInchargeId;
	
	private System.Nullable<int> _AssignedShippingDepartmentInchargeId;
	
	private System.Nullable<int> _AssignedSalesDepartmentIncharge;
	
	private System.Nullable<int> _StatusMasterId;
	
	private string _Fax;
	
	private System.Nullable<int> _AccountnameID;
	
	private string _id;
	
	private System.Nullable<int> _AccountBalanceLimitId;
	
	private string _Whid;
	
	private string _Zipcode;
	
	private System.Nullable<int> _PartyTypeCategoryNo;
	
	public Party_master()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyID", DbType="Int NOT NULL")]
	public int PartyID
	{
		get
		{
			return this._PartyID;
		}
		set
		{
			if ((this._PartyID != value))
			{
				this._PartyID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="Int")]
	public System.Nullable<int> Account
	{
		get
		{
			return this._Account;
		}
		set
		{
			if ((this._Account != value))
			{
				this._Account = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compname", DbType="NVarChar(MAX)")]
	public string Compname
	{
		get
		{
			return this._Compname;
		}
		set
		{
			if ((this._Compname != value))
			{
				this._Compname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contactperson", DbType="NVarChar(MAX)")]
	public string Contactperson
	{
		get
		{
			return this._Contactperson;
		}
		set
		{
			if ((this._Contactperson != value))
			{
				this._Contactperson = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(MAX)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this._Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(MAX)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(MAX)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this._State = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(MAX)")]
	public string Website
	{
		get
		{
			return this._Website;
		}
		set
		{
			if ((this._Website != value))
			{
				this._Website = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSTno", DbType="NVarChar(MAX)")]
	public string GSTno
	{
		get
		{
			return this._GSTno;
		}
		set
		{
			if ((this._GSTno != value))
			{
				this._GSTno = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incometaxno", DbType="NVarChar(MAX)")]
	public string Incometaxno
	{
		get
		{
			return this._Incometaxno;
		}
		set
		{
			if ((this._Incometaxno != value))
			{
				this._Incometaxno = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phoneno", DbType="NVarChar(MAX)")]
	public string Phoneno
	{
		get
		{
			return this._Phoneno;
		}
		set
		{
			if ((this._Phoneno != value))
			{
				this._Phoneno = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataopID", DbType="Int")]
	public System.Nullable<int> DataopID
	{
		get
		{
			return this._DataopID;
		}
		set
		{
			if ((this._DataopID != value))
			{
				this._DataopID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyTypeId", DbType="Int")]
	public System.Nullable<int> PartyTypeId
	{
		get
		{
			return this._PartyTypeId;
		}
		set
		{
			if ((this._PartyTypeId != value))
			{
				this._PartyTypeId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedAccountManagerId", DbType="Int")]
	public System.Nullable<int> AssignedAccountManagerId
	{
		get
		{
			return this._AssignedAccountManagerId;
		}
		set
		{
			if ((this._AssignedAccountManagerId != value))
			{
				this._AssignedAccountManagerId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedRecevingDepartmentInchargeId", DbType="Int")]
	public System.Nullable<int> AssignedRecevingDepartmentInchargeId
	{
		get
		{
			return this._AssignedRecevingDepartmentInchargeId;
		}
		set
		{
			if ((this._AssignedRecevingDepartmentInchargeId != value))
			{
				this._AssignedRecevingDepartmentInchargeId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedPurchaseDepartmentInchargeId", DbType="Int")]
	public System.Nullable<int> AssignedPurchaseDepartmentInchargeId
	{
		get
		{
			return this._AssignedPurchaseDepartmentInchargeId;
		}
		set
		{
			if ((this._AssignedPurchaseDepartmentInchargeId != value))
			{
				this._AssignedPurchaseDepartmentInchargeId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedShippingDepartmentInchargeId", DbType="Int")]
	public System.Nullable<int> AssignedShippingDepartmentInchargeId
	{
		get
		{
			return this._AssignedShippingDepartmentInchargeId;
		}
		set
		{
			if ((this._AssignedShippingDepartmentInchargeId != value))
			{
				this._AssignedShippingDepartmentInchargeId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedSalesDepartmentIncharge", DbType="Int")]
	public System.Nullable<int> AssignedSalesDepartmentIncharge
	{
		get
		{
			return this._AssignedSalesDepartmentIncharge;
		}
		set
		{
			if ((this._AssignedSalesDepartmentIncharge != value))
			{
				this._AssignedSalesDepartmentIncharge = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusMasterId", DbType="Int")]
	public System.Nullable<int> StatusMasterId
	{
		get
		{
			return this._StatusMasterId;
		}
		set
		{
			if ((this._StatusMasterId != value))
			{
				this._StatusMasterId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50)")]
	public string Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this._Fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountnameID", DbType="Int")]
	public System.Nullable<int> AccountnameID
	{
		get
		{
			return this._AccountnameID;
		}
		set
		{
			if ((this._AccountnameID != value))
			{
				this._AccountnameID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(500)")]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountBalanceLimitId", DbType="Int")]
	public System.Nullable<int> AccountBalanceLimitId
	{
		get
		{
			return this._AccountBalanceLimitId;
		}
		set
		{
			if ((this._AccountBalanceLimitId != value))
			{
				this._AccountBalanceLimitId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Whid", DbType="NVarChar(20)")]
	public string Whid
	{
		get
		{
			return this._Whid;
		}
		set
		{
			if ((this._Whid != value))
			{
				this._Whid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zipcode", DbType="NVarChar(50)")]
	public string Zipcode
	{
		get
		{
			return this._Zipcode;
		}
		set
		{
			if ((this._Zipcode != value))
			{
				this._Zipcode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyTypeCategoryNo", DbType="Int")]
	public System.Nullable<int> PartyTypeCategoryNo
	{
		get
		{
			return this._PartyTypeCategoryNo;
		}
		set
		{
			if ((this._PartyTypeCategoryNo != value))
			{
				this._PartyTypeCategoryNo = value;
			}
		}
	}
}
#pragma warning restore 1591
