#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="jobcenter.OADB")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCandidateMaster(CandidateMaster instance);
  partial void UpdateCandidateMaster(CandidateMaster instance);
  partial void DeleteCandidateMaster(CandidateMaster instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["jobcenter.OADBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<CandidateMaster> CandidateMasters
	{
		get
		{
			return this.GetTable<CandidateMaster>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CandidateMaster")]
public partial class CandidateMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _CandidateId;
	
	private System.Nullable<int> _PartyID;
	
	private System.Nullable<int> _DeptID;
	
	private System.Nullable<int> _DesignationMasterId;
	
	private System.Nullable<int> _StatusMasterId;
	
	private System.Nullable<int> _EmployeeTypeId;
	
	private System.Nullable<int> _AccountId;
	
	private System.Nullable<int> _AccountNo;
	
	private System.Nullable<int> _CountryId;
	
	private System.Nullable<int> _StateId;
	
	private System.Nullable<int> _City;
	
	private System.Nullable<int> _SuprviserId;
	
	private System.Nullable<int> _EducationqualificationID;
	
	private System.Nullable<int> _SpecialSubjectID;
	
	private System.Nullable<int> _yearofexperience;
	
	private System.Nullable<int> _Jobpositionid;
	
	private System.Nullable<int> _Whid;
	
	private string _Compid;
	
	private System.Nullable<bool> _Active;
	
	private string _LastName;
	
	private string _FirstName;
	
	private string _MiddleName;
	
	private string _CandidateNumber;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _SocialNo;
	
	private string _CandidatePhotoPath;
	
	private string _Address;
	
	private System.Nullable<System.DateTime> _EffectiveFrom;
	
	private string _ContactNo;
	
	private string _MobileNo;
	
	private System.Nullable<int> _sex;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCandidateIdChanging(long value);
    partial void OnCandidateIdChanged();
    partial void OnPartyIDChanging(System.Nullable<int> value);
    partial void OnPartyIDChanged();
    partial void OnDeptIDChanging(System.Nullable<int> value);
    partial void OnDeptIDChanged();
    partial void OnDesignationMasterIdChanging(System.Nullable<int> value);
    partial void OnDesignationMasterIdChanged();
    partial void OnStatusMasterIdChanging(System.Nullable<int> value);
    partial void OnStatusMasterIdChanged();
    partial void OnEmployeeTypeIdChanging(System.Nullable<int> value);
    partial void OnEmployeeTypeIdChanged();
    partial void OnAccountIdChanging(System.Nullable<int> value);
    partial void OnAccountIdChanged();
    partial void OnAccountNoChanging(System.Nullable<int> value);
    partial void OnAccountNoChanged();
    partial void OnCountryIdChanging(System.Nullable<int> value);
    partial void OnCountryIdChanged();
    partial void OnStateIdChanging(System.Nullable<int> value);
    partial void OnStateIdChanged();
    partial void OnCityChanging(System.Nullable<int> value);
    partial void OnCityChanged();
    partial void OnSuprviserIdChanging(System.Nullable<int> value);
    partial void OnSuprviserIdChanged();
    partial void OnEducationqualificationIDChanging(System.Nullable<int> value);
    partial void OnEducationqualificationIDChanged();
    partial void OnSpecialSubjectIDChanging(System.Nullable<int> value);
    partial void OnSpecialSubjectIDChanged();
    partial void OnyearofexperienceChanging(System.Nullable<int> value);
    partial void OnyearofexperienceChanged();
    partial void OnJobpositionidChanging(System.Nullable<int> value);
    partial void OnJobpositionidChanged();
    partial void OnWhidChanging(System.Nullable<int> value);
    partial void OnWhidChanged();
    partial void OnCompidChanging(string value);
    partial void OnCompidChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnCandidateNumberChanging(string value);
    partial void OnCandidateNumberChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnSocialNoChanging(string value);
    partial void OnSocialNoChanged();
    partial void OnCandidatePhotoPathChanging(string value);
    partial void OnCandidatePhotoPathChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEffectiveFromChanging(System.Nullable<System.DateTime> value);
    partial void OnEffectiveFromChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnsexChanging(System.Nullable<int> value);
    partial void OnsexChanged();
    #endregion
	
	public CandidateMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long CandidateId
	{
		get
		{
			return this._CandidateId;
		}
		set
		{
			if ((this._CandidateId != value))
			{
				this.OnCandidateIdChanging(value);
				this.SendPropertyChanging();
				this._CandidateId = value;
				this.SendPropertyChanged("CandidateId");
				this.OnCandidateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyID", DbType="Int")]
	public System.Nullable<int> PartyID
	{
		get
		{
			return this._PartyID;
		}
		set
		{
			if ((this._PartyID != value))
			{
				this.OnPartyIDChanging(value);
				this.SendPropertyChanging();
				this._PartyID = value;
				this.SendPropertyChanged("PartyID");
				this.OnPartyIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptID", DbType="Int")]
	public System.Nullable<int> DeptID
	{
		get
		{
			return this._DeptID;
		}
		set
		{
			if ((this._DeptID != value))
			{
				this.OnDeptIDChanging(value);
				this.SendPropertyChanging();
				this._DeptID = value;
				this.SendPropertyChanged("DeptID");
				this.OnDeptIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesignationMasterId", DbType="Int")]
	public System.Nullable<int> DesignationMasterId
	{
		get
		{
			return this._DesignationMasterId;
		}
		set
		{
			if ((this._DesignationMasterId != value))
			{
				this.OnDesignationMasterIdChanging(value);
				this.SendPropertyChanging();
				this._DesignationMasterId = value;
				this.SendPropertyChanged("DesignationMasterId");
				this.OnDesignationMasterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusMasterId", DbType="Int")]
	public System.Nullable<int> StatusMasterId
	{
		get
		{
			return this._StatusMasterId;
		}
		set
		{
			if ((this._StatusMasterId != value))
			{
				this.OnStatusMasterIdChanging(value);
				this.SendPropertyChanging();
				this._StatusMasterId = value;
				this.SendPropertyChanged("StatusMasterId");
				this.OnStatusMasterIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeId", DbType="Int")]
	public System.Nullable<int> EmployeeTypeId
	{
		get
		{
			return this._EmployeeTypeId;
		}
		set
		{
			if ((this._EmployeeTypeId != value))
			{
				this.OnEmployeeTypeIdChanging(value);
				this.SendPropertyChanging();
				this._EmployeeTypeId = value;
				this.SendPropertyChanged("EmployeeTypeId");
				this.OnEmployeeTypeIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int")]
	public System.Nullable<int> AccountId
	{
		get
		{
			return this._AccountId;
		}
		set
		{
			if ((this._AccountId != value))
			{
				this.OnAccountIdChanging(value);
				this.SendPropertyChanging();
				this._AccountId = value;
				this.SendPropertyChanged("AccountId");
				this.OnAccountIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", DbType="Int")]
	public System.Nullable<int> AccountNo
	{
		get
		{
			return this._AccountNo;
		}
		set
		{
			if ((this._AccountNo != value))
			{
				this.OnAccountNoChanging(value);
				this.SendPropertyChanging();
				this._AccountNo = value;
				this.SendPropertyChanged("AccountNo");
				this.OnAccountNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="Int")]
	public System.Nullable<int> CountryId
	{
		get
		{
			return this._CountryId;
		}
		set
		{
			if ((this._CountryId != value))
			{
				this.OnCountryIdChanging(value);
				this.SendPropertyChanging();
				this._CountryId = value;
				this.SendPropertyChanged("CountryId");
				this.OnCountryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", DbType="Int")]
	public System.Nullable<int> StateId
	{
		get
		{
			return this._StateId;
		}
		set
		{
			if ((this._StateId != value))
			{
				this.OnStateIdChanging(value);
				this.SendPropertyChanging();
				this._StateId = value;
				this.SendPropertyChanged("StateId");
				this.OnStateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="Int")]
	public System.Nullable<int> City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuprviserId", DbType="Int")]
	public System.Nullable<int> SuprviserId
	{
		get
		{
			return this._SuprviserId;
		}
		set
		{
			if ((this._SuprviserId != value))
			{
				this.OnSuprviserIdChanging(value);
				this.SendPropertyChanging();
				this._SuprviserId = value;
				this.SendPropertyChanged("SuprviserId");
				this.OnSuprviserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EducationqualificationID", DbType="Int")]
	public System.Nullable<int> EducationqualificationID
	{
		get
		{
			return this._EducationqualificationID;
		}
		set
		{
			if ((this._EducationqualificationID != value))
			{
				this.OnEducationqualificationIDChanging(value);
				this.SendPropertyChanging();
				this._EducationqualificationID = value;
				this.SendPropertyChanged("EducationqualificationID");
				this.OnEducationqualificationIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialSubjectID", DbType="Int")]
	public System.Nullable<int> SpecialSubjectID
	{
		get
		{
			return this._SpecialSubjectID;
		}
		set
		{
			if ((this._SpecialSubjectID != value))
			{
				this.OnSpecialSubjectIDChanging(value);
				this.SendPropertyChanging();
				this._SpecialSubjectID = value;
				this.SendPropertyChanged("SpecialSubjectID");
				this.OnSpecialSubjectIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearofexperience", DbType="Int")]
	public System.Nullable<int> yearofexperience
	{
		get
		{
			return this._yearofexperience;
		}
		set
		{
			if ((this._yearofexperience != value))
			{
				this.OnyearofexperienceChanging(value);
				this.SendPropertyChanging();
				this._yearofexperience = value;
				this.SendPropertyChanged("yearofexperience");
				this.OnyearofexperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jobpositionid", DbType="Int")]
	public System.Nullable<int> Jobpositionid
	{
		get
		{
			return this._Jobpositionid;
		}
		set
		{
			if ((this._Jobpositionid != value))
			{
				this.OnJobpositionidChanging(value);
				this.SendPropertyChanging();
				this._Jobpositionid = value;
				this.SendPropertyChanged("Jobpositionid");
				this.OnJobpositionidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Whid", DbType="Int")]
	public System.Nullable<int> Whid
	{
		get
		{
			return this._Whid;
		}
		set
		{
			if ((this._Whid != value))
			{
				this.OnWhidChanging(value);
				this.SendPropertyChanging();
				this._Whid = value;
				this.SendPropertyChanged("Whid");
				this.OnWhidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compid", DbType="NVarChar(50)")]
	public string Compid
	{
		get
		{
			return this._Compid;
		}
		set
		{
			if ((this._Compid != value))
			{
				this.OnCompidChanging(value);
				this.SendPropertyChanging();
				this._Compid = value;
				this.SendPropertyChanged("Compid");
				this.OnCompidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this.OnMiddleNameChanging(value);
				this.SendPropertyChanging();
				this._MiddleName = value;
				this.SendPropertyChanged("MiddleName");
				this.OnMiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateNumber", DbType="NVarChar(50)")]
	public string CandidateNumber
	{
		get
		{
			return this._CandidateNumber;
		}
		set
		{
			if ((this._CandidateNumber != value))
			{
				this.OnCandidateNumberChanging(value);
				this.SendPropertyChanging();
				this._CandidateNumber = value;
				this.SendPropertyChanged("CandidateNumber");
				this.OnCandidateNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocialNo", DbType="NVarChar(50)")]
	public string SocialNo
	{
		get
		{
			return this._SocialNo;
		}
		set
		{
			if ((this._SocialNo != value))
			{
				this.OnSocialNoChanging(value);
				this.SendPropertyChanging();
				this._SocialNo = value;
				this.SendPropertyChanged("SocialNo");
				this.OnSocialNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidatePhotoPath", DbType="NVarChar(50)")]
	public string CandidatePhotoPath
	{
		get
		{
			return this._CandidatePhotoPath;
		}
		set
		{
			if ((this._CandidatePhotoPath != value))
			{
				this.OnCandidatePhotoPathChanging(value);
				this.SendPropertyChanging();
				this._CandidatePhotoPath = value;
				this.SendPropertyChanged("CandidatePhotoPath");
				this.OnCandidatePhotoPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectiveFrom", DbType="Date")]
	public System.Nullable<System.DateTime> EffectiveFrom
	{
		get
		{
			return this._EffectiveFrom;
		}
		set
		{
			if ((this._EffectiveFrom != value))
			{
				this.OnEffectiveFromChanging(value);
				this.SendPropertyChanging();
				this._EffectiveFrom = value;
				this.SendPropertyChanged("EffectiveFrom");
				this.OnEffectiveFromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="NVarChar(50)")]
	public string ContactNo
	{
		get
		{
			return this._ContactNo;
		}
		set
		{
			if ((this._ContactNo != value))
			{
				this.OnContactNoChanging(value);
				this.SendPropertyChanging();
				this._ContactNo = value;
				this.SendPropertyChanged("ContactNo");
				this.OnContactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this.OnMobileNoChanging(value);
				this.SendPropertyChanging();
				this._MobileNo = value;
				this.SendPropertyChanged("MobileNo");
				this.OnMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="Int")]
	public System.Nullable<int> sex
	{
		get
		{
			return this._sex;
		}
		set
		{
			if ((this._sex != value))
			{
				this.OnsexChanging(value);
				this.SendPropertyChanging();
				this._sex = value;
				this.SendPropertyChanged("sex");
				this.OnsexChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class CountryMaster : CandidateMaster
{
	
	private int _CountryId;
	
	private string _CountryName;
	
	private string _Country_Code;
	
	private string _Phone_Code;
	
	private System.Nullable<bool> _active;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryIdChanging(int value);
    partial void OnCountryIdChanged();
    partial void OnCountryNameChanging(string value);
    partial void OnCountryNameChanged();
    partial void OnCountry_CodeChanging(string value);
    partial void OnCountry_CodeChanged();
    partial void OnPhone_CodeChanging(string value);
    partial void OnPhone_CodeChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
	
	public CountryMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int CountryId
	{
		get
		{
			return this._CountryId;
		}
		set
		{
			if ((this._CountryId != value))
			{
				this.OnCountryIdChanging(value);
				this.SendPropertyChanging();
				this._CountryId = value;
				this.SendPropertyChanged("CountryId");
				this.OnCountryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="NVarChar(50)")]
	public string CountryName
	{
		get
		{
			return this._CountryName;
		}
		set
		{
			if ((this._CountryName != value))
			{
				this.OnCountryNameChanging(value);
				this.SendPropertyChanging();
				this._CountryName = value;
				this.SendPropertyChanged("CountryName");
				this.OnCountryNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country_Code", DbType="NVarChar(50)")]
	public string Country_Code
	{
		get
		{
			return this._Country_Code;
		}
		set
		{
			if ((this._Country_Code != value))
			{
				this.OnCountry_CodeChanging(value);
				this.SendPropertyChanging();
				this._Country_Code = value;
				this.SendPropertyChanged("Country_Code");
				this.OnCountry_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Code", DbType="NVarChar(50)")]
	public string Phone_Code
	{
		get
		{
			return this._Phone_Code;
		}
		set
		{
			if ((this._Phone_Code != value))
			{
				this.OnPhone_CodeChanging(value);
				this.SendPropertyChanging();
				this._Phone_Code = value;
				this.SendPropertyChanged("Phone_Code");
				this.OnPhone_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
	public System.Nullable<bool> active
	{
		get
		{
			return this._active;
		}
		set
		{
			if ((this._active != value))
			{
				this.OnactiveChanging(value);
				this.SendPropertyChanging();
				this._active = value;
				this.SendPropertyChanged("active");
				this.OnactiveChanged();
			}
		}
	}
}

public partial class StateMasterTbl : CandidateMaster
{
	
	private int _StateId;
	
	private string _StateName;
	
	private string _CountryId;
	
	private string _State_Code;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStateIdChanging(int value);
    partial void OnStateIdChanged();
    partial void OnStateNameChanging(string value);
    partial void OnStateNameChanged();
    partial void OnCountryIdChanging(string value);
    partial void OnCountryIdChanged();
    partial void OnState_CodeChanging(string value);
    partial void OnState_CodeChanged();
    #endregion
	
	public StateMasterTbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int StateId
	{
		get
		{
			return this._StateId;
		}
		set
		{
			if ((this._StateId != value))
			{
				this.OnStateIdChanging(value);
				this.SendPropertyChanging();
				this._StateId = value;
				this.SendPropertyChanged("StateId");
				this.OnStateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateName", DbType="NVarChar(50)")]
	public string StateName
	{
		get
		{
			return this._StateName;
		}
		set
		{
			if ((this._StateName != value))
			{
				this.OnStateNameChanging(value);
				this.SendPropertyChanging();
				this._StateName = value;
				this.SendPropertyChanged("StateName");
				this.OnStateNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="NVarChar(50)")]
	public string CountryId
	{
		get
		{
			return this._CountryId;
		}
		set
		{
			if ((this._CountryId != value))
			{
				this.OnCountryIdChanging(value);
				this.SendPropertyChanging();
				this._CountryId = value;
				this.SendPropertyChanged("CountryId");
				this.OnCountryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State_Code", DbType="NVarChar(50)")]
	public string State_Code
	{
		get
		{
			return this._State_Code;
		}
		set
		{
			if ((this._State_Code != value))
			{
				this.OnState_CodeChanging(value);
				this.SendPropertyChanging();
				this._State_Code = value;
				this.SendPropertyChanged("State_Code");
				this.OnState_CodeChanged();
			}
		}
	}
}

public partial class CityMasterTbl : CandidateMaster
{
	
	private int _CityId;
	
	private string _CityName;
	
	private string _StateId;
	
	private string _Postalcodestart;
	
	private string _Postalcodeend;
	
	private System.Nullable<bool> _Active;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCityIdChanging(int value);
    partial void OnCityIdChanged();
    partial void OnCityNameChanging(string value);
    partial void OnCityNameChanged();
    partial void OnStateIdChanging(string value);
    partial void OnStateIdChanged();
    partial void OnPostalcodestartChanging(string value);
    partial void OnPostalcodestartChanged();
    partial void OnPostalcodeendChanging(string value);
    partial void OnPostalcodeendChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
	
	public CityMasterTbl()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityId", DbType="Int NOT NULL")]
	public int CityId
	{
		get
		{
			return this._CityId;
		}
		set
		{
			if ((this._CityId != value))
			{
				this.OnCityIdChanging(value);
				this.SendPropertyChanging();
				this._CityId = value;
				this.SendPropertyChanged("CityId");
				this.OnCityIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityName", DbType="NVarChar(50)")]
	public string CityName
	{
		get
		{
			return this._CityName;
		}
		set
		{
			if ((this._CityName != value))
			{
				this.OnCityNameChanging(value);
				this.SendPropertyChanging();
				this._CityName = value;
				this.SendPropertyChanged("CityName");
				this.OnCityNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", DbType="NVarChar(50)")]
	public string StateId
	{
		get
		{
			return this._StateId;
		}
		set
		{
			if ((this._StateId != value))
			{
				this.OnStateIdChanging(value);
				this.SendPropertyChanging();
				this._StateId = value;
				this.SendPropertyChanged("StateId");
				this.OnStateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postalcodestart", DbType="NVarChar(50)")]
	public string Postalcodestart
	{
		get
		{
			return this._Postalcodestart;
		}
		set
		{
			if ((this._Postalcodestart != value))
			{
				this.OnPostalcodestartChanging(value);
				this.SendPropertyChanging();
				this._Postalcodestart = value;
				this.SendPropertyChanged("Postalcodestart");
				this.OnPostalcodestartChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postalcodeend", DbType="NVarChar(50)")]
	public string Postalcodeend
	{
		get
		{
			return this._Postalcodeend;
		}
		set
		{
			if ((this._Postalcodeend != value))
			{
				this.OnPostalcodeendChanging(value);
				this.SendPropertyChanging();
				this._Postalcodeend = value;
				this.SendPropertyChanged("Postalcodeend");
				this.OnPostalcodeendChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
}
#pragma warning restore 1591
